name: Test Runner

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Test Runner
        run: |
          echo "Hello from EC2"
          hostname
          pwd
